apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-gitops-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hannu1992/nest-gitops-k8s.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas    
