apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-gitops
spec:
  replicas: 2   # HPA will control this at runtime
  selector:
    matchLabels:
      app: nest-gitops
  template:
    metadata:
      labels:
        app: nest-gitops
    spec:
      containers:
      - name: app
        image: hannumannamdev1992/nest-gitops:bb980a3
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nest-gitops-config
        - secretRef:
            name: nest-gitops-secret
        resources:                 # ✅ INSIDE container
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
