apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-gitops
  template:
    metadata:
      labels:
        app: nest-gitops
    spec:
      containers:
      - name: app
        image: hannumannamdev1992/nest-gitops:bb980a3
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nest-gitops-config
        - secretRef:
            name: nest-gitops-secret
